defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  output_subdir: null
  run:
    dir: .

models:
  object_detector:
    weights_path: /home/rizvan/f22/pmldl/project/asl-recognition/yolov5/runs/train/yolov5x/weights/best.pt
    conf_thresh: 0.2
  classifier:
    weights_path: /home/rizvan/f22/pmldl/project/asl-recognition/weights/classifier/vgg16
    classes: [
      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K',
      'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V',
      'W', 'X', 'Y', 'Z', 'nothing', 'space', 'del'
    ]
use_classifier: True
device: cuda:0
test_video_path: /home/rizvan/f22/pmldl/project/asl-recognition/data/demo/demo_asl_crf30.mov
save_dir: results
